os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
script:
  - xcode-select --install
  - eval "$(curl -sL https://gist.githubusercontent.com/calebkleveter/adbc184c15d25a15914d91b7497bdcd4/raw/a2beda20255a59d872d95d6254e032f4f138296b/TravisPodLint.sh)"
